# Utilisation de l'image Node.js officielle
FROM node:18

# Crée un répertoire de travail
WORKDIR /app

# Copie le package.json et package-lock.json
COPY package*.json ./

# Installe les dépendances
RUN npm install

# Copie tout le reste du code
COPY . .

# Expose le port 3000
EXPOSE 3000

# Démarre l'application en mode développement
CMD ["npm", "start"]
