# Utilisation de l'image Node.js officielle
FROM node:18

# Crée un répertoire de travail
WORKDIR /app

# Copie le package.json et package-lock.json
COPY package*.json ./

# Installe les dépendances
RUN npm install

# Copie tout le reste du code
COPY . .

# Expose le port 5000
EXPOSE 5000

# Commande pour démarrer l'application
CMD ["node", "server.js"]
